/**
 * The icon set, in one place.
 *
 * Phosphor, imported from its SSR entry point so the same icons work in server
 * and client components. Everything is drawn at a single weight and a single
 * optical size — an icon set reads as designed when it is consistent, and as
 * clip-art when every glyph comes from somewhere different.
 *
 * `regular` is the working weight; `duotone` appears only where an icon is the
 * subject rather than a label, which is a handful of places.
 */
export {
  // navigation and chrome
  Compass,
  MagnifyingGlass,
  SlidersHorizontal,
  Gauge,
  SignOut,
  User,
  CaretRight,
  CaretLeft,
  CaretDown,
  ArrowRight,
  ArrowLeft,
  CaretUp,
  X,
  Plus,
  DotsThree,
  List,
  SquaresFour,
  ArrowUpRight,
  Keyboard,
  EnvelopeSimple,
  LockSimple,

  // theme
  Sun,
  Moon,
  Monitor,

  // the domain
  Exam,
  Books,
  GraduationCap,
  Stack,
  ListNumbers,
  Timer,
  Clock,
  ClockCountdown,
  Hourglass,
  Pause,
  ListChecks,
  Target,
  Lightning,
  TrendDown,
  Question,
  BookOpenText,
  Notebook,
  SealCheck,
  PencilSimpleLine,
  Play,
  Check,
  CheckCircle,
  XCircle,
  MinusCircle,
  Flag,
  BookmarkSimple,
  ChatCircleText,
  Warning,
  WarningCircle,
  Info,
  Lightbulb,
  VideoCamera,
  Function as FunctionIcon,
  Table,
  Code,
  TreeStructure,
  ChartBar,
  Image as ImageIcon,
  Database,

  // teaching: the desk, the studio and the recorder
  ChalkboardTeacher,
  Microphone,
  MicrophoneSlash,
  // Aliased, because a bare `Record` would shadow TypeScript's Record<K, V>.
  Record as RecordIcon,
  Stop,
  VideoCameraSlash,
  UploadSimple,
  DownloadSimple,
  YoutubeLogo,
  LinkSimple,
  Copy,
  Shuffle,

  // the whiteboard
  PencilSimple,
  Highlighter,
  Eraser,
  HandPointing,
  LineSegment,
  Square,
  Circle,
  TextT,
  Scribble,
  Palette,
  GridFour,
  DotsNine,
  PushPin,
  ArrowUUpLeft,
  ArrowUUpRight,
  Broom,
  FilePlus,

  // admin
  Upload,
  Tree,
  FileText,
  Queue,
  ShieldCheck,
  Trash,
  Eye,
  EyeSlash,
  FloppyDisk,
  ArrowCounterClockwise,
  ArrowsClockwise,
  Sparkle,
  Users,
  UserPlus,
  UserMinus,
  // the teaching studio's board
  Article,
  CornersIn,
  CornersOut,
} from '@phosphor-icons/react/ssr'
